const form = document.querySelector('form');
const output = document.querySelector('#output');

const ideas = [
  "Juniors should focus on HTML, CSS and JS instead of frameworks, here's why",
  'React is terrible and it ruined my day',
  'View Transitions and speculative rendering: why MPAs have a comeback',
  'New Map and Set methods in JS',
  'You need to try CSS container queries',
  'How to not spend $10,000 on AWS',
  "I tried writing my own JS framework so you don't have to",
  'CSS rem vs em',
  'Is Tailwind really that bad? Yes.',
  "5 HTML elements you should likely know but don't",
  'HTML popovers vs dialogs',
  'Can I hear your website?',
  'Should you generate alt text with AI?',
  'How does AI change the a11y landscape?',
  'Do we have too many web APIs?',
  "Why aren't PWAs more popular?",
  'How to start a local tech meetup',
  'How to give an engaging tech talk',
  'Do you really know the CSS cascade?',
  'TypeScript: Safety net or developer crutch?',
  'Framework churn is burning out developers — what now?',
  'HTML is a backend problem now',
  "The web is fast, your code isn't",
  'WebAssembly in 2025: What can you actually use it for?',
  "Why you're sleeping on the Web Share API",
  'Forget :hover — CSS @scroll-timeline is here',
  'Why WebRTC still feels like magic',
  "The myth of 'vanilla JS': What it really means to go framework-free",
  'What if the web had versioning?',
  'The dark side of DX: when developer experience ruins user experience',
  'The web’s secret layout engine: Writing Modes',
  "Everything is a form: accessible UI patterns you're misusing",
  'The JS event loop, visualized — again, but better',
  'Why your single-page app should be a multi-page app',
  'Building animations without JavaScript: CSS is enough',
  'Why you should stop using divs for everything',
  "Client Components vs Server Components: React's identity crisis",
  'How good is too good? When UX starts to feel fake',
  "Forms are still broken — here's how to fix them",
  'Are you accidentally making your site unusable with prefers-reduced-motion?',
  'The uncanny valley of loading skeletons',
  'Stop breaking the back button: routing done right',
  'Web Components: still underrated, still weird',
  'The hidden power of the <label> element',
  'Do we still need responsive design in 2025?',
  "You don't need JS for dropdowns — seriously",
  'Light DOM vs Shadow DOM: what even is happening?',
  'The anatomy of a perfect button',
  'Is it time to ditch media queries for container queries?',
  "What's wrong with your CSS naming conventions?",
  'Can we stop arguing about Tailwind now?',
  'Semantic HTML is not just for screen readers',
  "You don't need a design system, you need discipline",
  'Stop re-rendering everything: smarter state management strategies',
  'Progressive enhancement is not dead',
  'Why you should care about the DOM lifecycle',
  'The hidden cost of hydration',
  'Frameworkless web apps: myth or movement?',
  'Why web performance is your responsibility',
  'The many lives of position: absolute',
  'Why your Lighthouse score is lying to you',
  "Dark mode isn't just a toggle",
  'CSS Grid vs Flexbox: when to use which',
  'The art of minimal JavaScript',
  'Declarative UI: more than just JSX',
  'Do you really need that animation?',
  'Custom elements in real-world applications',
  'The return of progressive web apps',
  'Making SPAs feel like MPAs',
  'Why native form controls are better than you think',
  'Stop fighting the browser',
  'One file ,one component: a scalable frontend structure',
  'Why most loading spinners are a lie',
  'How to write future-proof CSS',
  'JavaScript fatigue: surviving the ecosystem',
  'Writing HTML with intent',
  'You’re probably using z-index wrong',
  'Browser defaults are your friend',
  'Declarative animations with the View Transitions API',
  'CSS nesting: writing cleaner styles without a preprocessor',
  'Reactivity is not magic: how frameworks track state',
  'Better design with fewer breakpoints',
  'Modern CSS is finally good enough',
  'Stop bundling everything',
  'Understanding the render tree for real performance gains',
  'From display: contents to chaos: the hidden dangers',
  'The illusion of control with CSS resets',
  "Accessibility for developers who think they don't need it",
  "Web typography: don't just pick a Google Font",
  'Styling forms is still a nightmare — here’s how to fix it',
  'The end of pixels: thinking in relative units',
  'How I broke the web with one overflow: hidden',
  'Writing semantic markup in a component-driven world',
  'CSS variables are more powerful than you think',
  'Forget BEM — let your components own their styles',
  'When CSS specificity bites you',
  'Responsive design without media queries',
  'The new cascade layers in CSS: why they matter',
  'Stop ignoring motion preferences',
  'Making web apps feel native (without hurting the web)',
  'Can we have nice things? Native dialogs in 2025',
  'Stateful vs stateless UI: a design systems problem',
  'Why hydration isn’t real-time rendering',
  'The anatomy of a fast paint',
  'HTML is already accessible — until you mess it up',
  'You don’t need a modal library',
  'Building trust with form UX',
  'Do less: building better interfaces by removing features',
  'Death to 800ms transitions',
  'Animations that don’t suck',
  'Bridging the gap between design systems and actual design',
  'The invisible power of the focus ring',
  'You’re not accounting for pointer types',
  'CSS container queries in production: what I learned',
  'Make fewer divs',
  "Stop styling components like it's 2015",
  'Your icon system is probably broken',
  'The case for native select menus',
  'Responsive images: the right way',
  'You can’t escape layout shifts (but you can reduce them)',
  'Does your component really need to be reusable?',
  'Code splitting for humans',
  'How to design developer-friendly components',
  'Semantic markup for non-semantics fans',
  'When JavaScript should not be your first choice',
  'The UX cost of modals',
  'Why accordions are accessibility traps',
  'Drop your CSS framework ,not your consistency',
  'Atomic design is not a silver bullet',
  'Real inclusive design: beyond screen readers',
  'Do you really need icons in your inputs?',
  'Overengineering the frontend: a cautionary tale',
  'The browser is a runtime — treat it like one',
  'You don’t need ARIA if your HTML is good',
  'Modern frontend without npm',
  'From pixels to performance budgets',
  'How visual regressions destroy trust',
  'Everything is a list — design accordingly',
  'CSS scroll snap: good in theory ,dangerous in practice',
  'The fall of the global stylesheet',
  'Debugging layout without DevTools',
  'When inline styles actually make sense',
  'Making accessibility part of your design process',
  'The case for fewer animations',
  'The myth of the consistent component library',
  'The UX of error messages',
  'Modern form validation without libraries',
  'Building interfaces for interruption',
  'Mobile-first is not mobile-only',
  'Stop reinventing the tooltip',
  'The progressive stack: HTML first ,JS later',
  "You don't need a frontend build tool (probably)",
  'Performance-first design: what that actually means',
  'Why you should stop hiding content behind interactions',
  'Zero JavaScript interfaces: the new frontier',
  "AI isn't fixing accessibility — you are",
  'Writing frontend code that lasts',
  'Stop calling everything a modal',
  'How to keep users oriented in complex UIs',
  'Why native form controls are better than you think',
  'Stop fighting the browser',
  'One file ,one component: a scalable frontend structure',
  'Why most loading spinners are a lie',
  'Stop re-rendering everything: smarter state management strategies',
  'Progressive enhancement is not dead',
  'Why you should care about the DOM lifecycle',
  'The hidden cost of hydration',
  'Frameworkless web apps: myth or movement?',
  'Why web performance is your responsibility',
  'The many lives of `position: absolute`',
  'Why your Lighthouse score is lying to you',
  "Dark mode isn't just a toggle",
  'CSS Grid vs Flexbox: when to use which',
  'The art of minimal JavaScript',
  'Declarative UI: more than just JSX',
  'Do you really need that animation?',
  'Custom elements in real-world applications',
  'The return of progressive web apps',
  'Making SPAs feel like MPAs',
  'Why native form controls are better than you think',
  'Stop fighting the browser',
  'One file ,one component: a scalable frontend structure',
  'Why most loading spinners are a lie',
  'Stop re-rendering everything: smarter state management strategies',
  'Progressive enhancement is not dead',
  'Why you should care about the DOM lifecycle',
  'The hidden cost of hydration',
  'Frameworkless web apps: myth or movement?',
  'Why web performance is your responsibility',
  'The many lives of `position: absolute`',
  'Why your Lighthouse score is lying to you',
  "Dark mode isn't just a toggle",
  'CSS Grid vs Flexbox: when to use which',
  'The art of minimal JavaScript',
  'Declarative UI: more than just JSX',
  'Do you really need that animation?',
  'Custom elements in real-world applications',
  'The return of progressive web apps',
  'Making SPAs feel like MPAs',
  'Why native form controls are better than you think',
  'Stop fighting the browser',
  'One file ,one component: a scalable frontend structure',
  'Why most loading spinners are a lie',
  'Stop re-rendering everything: smarter state management strategies',
  'Progressive enhancement is not dead',
  'Why you should care about the DOM lifecycle',
  'The hidden cost of hydration',
  'Frameworkless web apps: myth or movement?',
  'Why web performance is your responsibility',
  'The many lives of `position: absolute`',
  'Why your Lighthouse score is lying to you',
  "Dark mode isn't just a toggle",
  'CSS Grid vs Flexbox: when to use which',
  'The art of minimal JavaScript',
  'Declarative UI: more than just JSX',
  'Do you really need that animation?',
  'Custom elements in real-world applications',
  'The return of progressive web apps',
  'Making SPAs feel like MPAs',
  'Why native form controls are better than you think',
  'Stop fighting the browser',
  'One file ,one component: a scalable frontend structure',
  'Why most loading spinners are a lie',
  'Stop re-rendering everything: smarter state management strategies',
  'Progressive enhancement is not dead',
  'Why you should care about the DOM lifecycle',
  'The hidden cost of hydration',
  'Frameworkless web apps: myth or movement?',
  'Why web performance is your responsibility',
  'The many lives of `position: absolute`',
  'Why your Lighthouse score is lying to you',
  "Dark mode isn't just a toggle",
  'CSS Grid vs Flexbox: when to use which',
  'The art of minimal JavaScript',
  'Declarative UI: more than just JSX',
  'Do you really need that animation?',
  'Custom elements in real-world applications',
  'The return of progressive web apps',
  'Making SPAs feel like MPAs',
  'Why native form controls are better than you think',
  'Stop fighting the browser',
  'One file ,one component: a scalable frontend structure',
  'Why most loading spinners are a lie',
  'Stop re-rendering everything: smarter state management strategies',
  'Progressive enhancement is not dead',
  'Why you should care about the DOM lifecycle',
  'The hidden cost of hydration',
  'Frameworkless web apps: myth or movement?',
  'Why web performance is your responsibility',
  'The many lives of `position: absolute`',
  'Why your Lighthouse score is lying to you',
  "Dark mode isn't just a toggle",
  'CSS Grid vs Flexbox: when to use which',
  'The art of minimal JavaScript',
  'Declarative UI: more than just JSX',
  'Do you really need that animation?',
  'Custom elements in real-world applications',
  'The return of progressive web apps',
  'Making SPAs feel like MPAs',
  'Why native form controls are better than you think',
  'Stop fighting the browser',
  'One file ,one component: a scalable frontend structure',
  'Why most loading spinners are a lie',
  'Stop re-rendering everything: smarter state management strategies',
  'Progressive enhancement is not dead',
  'Why you should care about the DOM lifecycle',
  'The hidden cost of hydration',
  'Frameworkless web apps: myth or movement?',
  'Why web performance is your responsibility',
  'The many lives of `position: absolute`',
  'Why your Lighthouse score is lying to you',
  "Dark mode isn't just a toggle",
  'CSS Grid vs Flexbox: when to use which',
  'The art of minimal JavaScript',
  'Declarative UI: more than just JSX',
  'Do you really need that animation?',
  'Custom elements in real-world applications',
  'The return of progressive web apps',
  'Making SPAs feel like MPAs',
  'Why native form controls are better than you think',
  'Stop fighting the browser',
  'One file, one component: a scalable frontend structure',
  'Why most loading spinners are a lie',
  'Stop re-rendering everything: smarter state management strategies',
  'Progressive enhancement is not dead',
  'Why you should care about the DOM lifecycle',
  'The hidden cost of hydration',
  'Frameworkless web apps: myth or movement?',
  'Why web performance is your responsibility',
  'The many lives of `position: absolute`',
  'Why your Lighthouse score is lying to you',
  "Dark mode isn't just a toggle",
  'CSS Grid vs Flexbox: when to use which',
  'The art of minimal JavaScript',
  'Declarative UI: more than just JSX',
  'Do you really need that animation?',
  'Custom elements in real-world applications',
  'The return of progressive web apps',
  'Making SPAs feel like MPAs',
  'Why native form controls are better than you think',
  'Stop fighting the browser',
  'One file, one component: a scalable frontend structure',
  'Why most loading spinners are a lie',
  'Stop re-rendering everything: smarter state management strategies',
  'Progressive enhancement is not dead',
  'Why you should care about the DOM lifecycle',
  'The hidden cost of hydration',
  'Frameworkless web apps: myth or movement?',
  'Why web performance is your responsibility',
  'The many lives of `position: absolute`',
  'Why your Lighthouse score is lying to you',
  "Dark mode isn't just a toggle",
  'CSS Grid vs Flexbox: when to use which',
  'The art of minimal JavaScript',
  'Declarative UI: more than just JSX',
  'Do you really need that animation?',
  'Custom elements in real-world applications',
  'The return of progressive web apps',
  'Making SPAs feel like MPAs',
  'Why native form controls are better than you think',
  'Stop fighting the browser',
  'One file, one component: a scalable frontend structure',
  'Why most loading spinners are a lie',
  'Stop re-rendering everything: smarter state management strategies',
  'Progressive enhancement is not dead',
  'Why you should care about the DOM lifecycle',
  'The hidden cost of hydration',
  'Frameworkless web apps: myth or movement?',
  'Why web performance is your responsibility',
  'The many lives of `position: absolute`',
  'Why your Lighthouse score is lying to you',
  "Dark mode isn't just a toggle",
  'CSS Grid vs Flexbox: when to use which',
  'The art of minimal JavaScript',
  'Declarative UI: more than just JSX',
  'Do you really need that animation?',
  'Custom elements in real-world applications',
  'The return of progressive web apps',
  'Making SPAs feel like MPAs',
  'Why native form controls are better than you think',
  'Stop fighting the browser',
  'One file, one component: a scalable frontend structure',
  'Why most loading spinners are a lie',
  'Stop re-rendering everything: smarter state management strategies',
  'Progressive enhancement is not dead',
  'Why you should care about the DOM lifecycle',
  'The hidden cost of hydration',
  'Frameworkless web apps: myth or movement?',
  'Why web performance is your responsibility',
  'The many lives of `position: absolute`',
  'Why your Lighthouse score is lying to you',
  "Dark mode isn't just a toggle",
  'CSS Grid vs Flexbox: when to use which',
  'The art of minimal JavaScript',
  'Declarative UI: more than just JSX',
  'Do you really need that animation?',
  'Custom elements in real-world applications',
  'The return of progressive web apps',
  'Making SPAs feel like MPAs',
  'Why native form controls are better than you think',
  'Stop fighting the browser',
  'One file, one component: a scalable frontend structure',
  'Why most loading spinners are a lie',
  'Stop re-rendering everything: smarter state management strategies',
  'Progressive enhancement is not dead',
  'Why you should care about the DOM lifecycle',
  'The hidden cost of hydration',
  'Frameworkless web apps: myth or movement?',
  'Why web performance is your responsibility',
  'The many lives of `position: absolute`',
  'Why your Lighthouse score is lying to you',
  "Dark mode isn't just a toggle",
  'CSS Grid vs Flexbox: when to use which',
  'The art of minimal JavaScript',
  'Declarative UI: more than just JSX',
  'Do you really need that animation?',
  'Custom elements in real-world applications',
  'The return of progressive web apps',
  'Making SPAs feel like MPAs',
  'Why native form controls are better than you think',
  'Stop fighting the browser',
  'One file, one component: a scalable frontend structure',
  'Why most loading spinners are a lie',
  'Stop re-rendering everything: smarter state management strategies',
  'Progressive enhancement is not dead',
  'Why you should care about the DOM lifecycle',
  'The hidden cost of hydration',
  'Frameworkless web apps: myth or movement?',
  'Why web performance is your responsibility',
  'The many lives of `position: absolute`',
  'Why your Lighthouse score is lying to you',
  "Dark mode isn't just a toggle",
  'CSS Grid vs Flexbox: when to use which',
  'The art of minimal JavaScript',
  'Declarative UI: more than just JSX',
  'Do you really need that animation?',
  'Custom elements in real-world applications',
  'The return of progressive web apps',
  'Making SPAs feel like MPAs',
  'Why native form controls are better than you think',
  'Stop fighting the browser',
  'One file, one component: a scalable frontend structure',
  'Why most loading spinners are a lie',
  'Stop re-rendering everything: smarter state management strategies',
  'Progressive enhancement is not dead',
  'Why you should care about the DOM lifecycle',
  'The hidden cost of hydration',
  'Frameworkless web apps: myth or movement?',
  'Why web performance is your responsibility',
  'The many lives of `position: absolute`',
  'Why your Lighthouse score is lying to you',
  "Dark mode isn't just a toggle",
  'CSS Grid vs Flexbox: when to use which',
  'The art of minimal JavaScript',
  'Declarative UI: more than just JSX',
  'Do you really need that animation?',
  'Custom elements in real-world applications',
  'The return of progressive web apps',
  'Making SPAs feel like MPAs',
  'Why native form controls are better than you think',
  'Stop fighting the browser',
  'One file, one component: a scalable frontend structure',
  'Why most loading spinners are a lie',
  'Stop re-rendering everything: smarter state management strategies',
  'Progressive enhancement is not dead',
  'Why you should care about the DOM lifecycle',
  'The hidden cost of hydration',
  'Frameworkless web apps: myth or movement?',
  'Why web performance is your responsibility',
  'The many lives of `position: absolute`',
  'Why your Lighthouse score is lying to you',
  "Dark mode isn't just a toggle",
  'CSS Grid vs Flexbox: when to use which',
  'The art of minimal JavaScript',
  'Declarative UI: more than just JSX',
  'Do you really need that animation?',
  'Custom elements in real-world applications',
  'The return of progressive web apps',
  'Making SPAs feel like MPAs',
  'Why native form controls are better than you think',
  'Stop fighting the browser',
  'One file, one component: a scalable frontend structure',
  'Why most loading spinners are a lie',
  'Stop re-rendering everything: smarter state management strategies',
  'Progressive enhancement is not dead',
  'Why you should care about the DOM lifecycle',
  'The hidden cost of hydration',
  'Frameworkless web apps: myth or movement?',
  'Why web performance is your responsibility',
  'The many lives of `position: absolute`',
  'Why your Lighthouse score is lying to you',
  "Dark mode isn't just a toggle",
  'CSS Grid vs Flexbox: when to use which',
  'The art of minimal JavaScript',
  'Declarative UI: more than just JSX',
  'Do you really need that animation?',
  'Custom elements in real-world applications',
  'The return of progressive web apps',
  'Making SPAs feel like MPAs',
  'Why native form controls are better than you think',
  'Stop fighting the browser',
  'One file, one component: a scalable frontend structure',
  'Why most loading spinners are a lie',
  'Stop re-rendering everything: smarter state management strategies',
  'Progressive enhancement is not dead',
  'Why you should care about the DOM lifecycle',
  'The hidden cost of hydration',
  'Frameworkless web apps: myth or movement?',
  'Why web performance is your responsibility',
  'The many lives of `position: absolute`',
  'Why your Lighthouse score is lying to you',
  "Dark mode isn't just a toggle",
  'CSS Grid vs Flexbox: when to use which',
  'The art of minimal JavaScript',
  'Declarative UI: more than just JSX',
  'Do you really need that animation?',
  'Custom elements in real-world applications',
  'The return of progressive web apps',
  'Making SPAs feel like MPAs',
  'Why native form controls are better than you think',
  'Stop fighting the browser',
  'One file, one component: a scalable frontend structure',
  'Why most loading spinners are a lie',
  'Stop re-rendering everything: smarter state management strategies',
  'Progressive enhancement is not dead',
  'Why you should care about the DOM lifecycle',
  'The hidden cost of hydration',
  'Frameworkless web apps: myth or movement?',
  'Why web performance is your responsibility',
  'The many lives of `position: absolute`',
  'Why your Lighthouse score is lying to you',
  "Dark mode isn't just a toggle",
  'CSS Grid vs Flexbox: when to use which',
  'The art of minimal JavaScript',
  'Declarative UI: more than just JSX',
  'Do you really need that animation?',
  'Custom elements in real-world applications',
  'The return of progressive web apps',
  'Making SPAs feel like MPAs',
  'Why native form controls are better than you think',
  'Stop fighting the browser',
  'One file, one component: a scalable frontend structure',
  'Why most loading spinners are a lie',
  'Stop re-rendering everything: smarter state management strategies',
  'Progressive enhancement is not dead',
  'Why you should care about the DOM lifecycle',
  'The hidden cost of hydration',
  'Frameworkless web apps: myth or movement?',
  'Why web performance is your responsibility',
  'The many lives of `position: absolute`',
  'Why your Lighthouse score is lying to you',
  "Dark mode isn't just a toggle",
  'CSS Grid vs Flexbox: when to use which',
  'The art of minimal JavaScript',
  'Declarative UI: more than just JSX',
  'Do you really need that animation?',
  'Custom elements in real-world applications',
  'The return of progressive web apps',
  'Making SPAs feel like MPAs',
  'Why native form controls are better than you think',
  'Stop fighting the browser',
  'One file, one component: a scalable frontend structure',
  'Why most loading spinners are a lie',
  'Stop re-rendering everything: smarter state management strategies',
  'Progressive enhancement is not dead',
  'Why you should care about the DOM lifecycle',
  'The hidden cost of hydration',
  'Frameworkless web apps: myth or movement?',
  'Why web performance is your responsibility',
  'The many lives of `position: absolute`',
  'Why your Lighthouse score is lying to you',
  "Dark mode isn't just a toggle",
  'CSS Grid vs Flexbox: when to use which',
  'The art of minimal JavaScript',
  'Declarative UI: more than just JSX',
  'Do you really need that animation?',
  'Custom elements in real-world applications',
  'The return of progressive web apps',
  'Making SPAs feel like MPAs',
  'Why native form controls are better than you think',
  'Stop fighting the browser',
  'One file, one component: a scalable frontend structure',
  'Why most loading spinners are a lie',
  'Stop re-rendering everything: smarter state management strategies',
  'Progressive enhancement is not dead',
  'Why you should care about the DOM lifecycle',
  'The hidden cost of hydration',
  'Frameworkless web apps: myth or movement?',
  'Why web performance is your responsibility',
  'The many lives of `position: absolute`',
  'Why your Lighthouse score is lying to you',
  "Dark mode isn't just a toggle",
  'CSS Grid vs Flexbox: when to use which',
  'The art of minimal JavaScript',
  'Declarative UI: more than just JSX',
  'Do you really need that animation?',
  'Custom elements in real-world applications',
  'The return of progressive web apps',
  'Making SPAs feel like MPAs',
  'Why native form controls are better than you think',
  'Stop fighting the browser',
  'One file, one component: a scalable frontend structure',
  'Why most loading spinners are a lie',
  'Stop re-rendering everything: smarter state management strategies',
  'Progressive enhancement is not dead',
  'Why you should care about the DOM lifecycle',
  'The hidden cost of hydration',
  'Frameworkless web apps: myth or movement?',
  'Why web performance is your responsibility',
  'The many lives of `position: absolute`',
  'Why your Lighthouse score is lying to you',
  "Dark mode isn't just a toggle",
  'CSS Grid vs Flexbox: when to use which',
  'The art of minimal JavaScript',
  'Declarative UI: more than just JSX',
  'Do you really need that animation?',
  'Custom elements in real-world applications',
  'The return of progressive web apps',
  'Making SPAs feel like MPAs',
  'Why native form controls are better than you think',
  'Stop fighting the browser',
  'One file, one component: a scalable frontend structure',
  'Why most loading spinners are a lie',
  'Stop re-rendering everything: smarter state management strategies',
  'Progressive enhancement is not dead',
  'Why you should care about the DOM lifecycle',
  'The hidden cost of hydration',
  'Frameworkless web apps: myth or movement?',
  'Why web performance is your responsibility',
  'The many lives of `position: absolute`',
  'Why your Lighthouse score is lying to you',
  "Dark mode isn't just a toggle",
  'CSS Grid vs Flexbox: when to use which',
  'The art of minimal JavaScript',
  'Declarative UI: more than just JSX',
  'Do you really need that animation?',
  'Custom elements in real-world applications',
  'The return of progressive web apps',
  'Making SPAs feel like MPAs',
  'Why native form controls are better than you think',
  'Stop fighting the browser',
  'One file, one component: a scalable frontend structure',
  'Why most loading spinners are a lie',
  'Stop re-rendering everything: smarter state management strategies',
  'Progressive enhancement is not dead',
  'Why you should care about the DOM lifecycle',
  'The hidden cost of hydration',
  'Frameworkless web apps: myth or movement?',
  'Why web performance is your responsibility',
  'The many lives of `position: absolute`',
  'Why your Lighthouse score is lying to you',
  "Dark mode isn't just a toggle",
  'CSS Grid vs Flexbox: when to use which',
  'The art of minimal JavaScript',
  'Declarative UI: more than just JSX',
  'Do you really need that animation?',
  'Custom elements in real-world applications',
  'The return of progressive web apps',
  'Making SPAs feel like MPAs',
  'Why native form controls are better than you think',
  'Stop fighting the browser',
  'One file, one component: a scalable frontend structure',
  'Why most loading spinners are a lie',
  'Stop re-rendering everything: smarter state management strategies',
  'Progressive enhancement is not dead',
  'Why you should care about the DOM lifecycle',
  'The hidden cost of hydration',
  'Frameworkless web apps: myth or movement?',
  'Why web performance is your responsibility',
  'The many lives of `position: absolute`',
  'Why your Lighthouse score is lying to you',
  "Dark mode isn't just a toggle",
  'CSS Grid vs Flexbox: when to use which',
  'The art of minimal JavaScript',
  'Declarative UI: more than just JSX',
  'Do you really need that animation?',
  'Custom elements in real-world applications',
  'The return of progressive web apps',
  'Making SPAs feel like MPAs',
  'Why native form controls are better than you think',
  'Stop fighting the browser',
  'One file, one component: a scalable frontend structure',
  'Why most loading spinners are a lie',
  'Stop re-rendering everything: smarter state management strategies',
  'Progressive enhancement is not dead',
  'Why you should care about the DOM lifecycle',
  'The hidden cost of hydration',
  'Frameworkless web apps: myth or movement?',
  'Why web performance is your responsibility',
  'The many lives of `position: absolute`',
  'Why your Lighthouse score is lying to you',
  "Dark mode isn't just a toggle",
  'CSS Grid vs Flexbox: when to use which',
  'The art of minimal JavaScript',
  'Declarative UI: more than just JSX',
  'Do you really need that animation?',
  'Custom elements in real-world applications',
  'The return of progressive web apps',
  'Making SPAs feel like MPAs',
  'Why native form controls are better than you think',
  'Stop fighting the browser',
  'One file, one component: a scalable frontend structure',
  'Why most loading spinners are a lie',
  'Stop re-rendering everything: smarter state management strategies',
  'Progressive enhancement is not dead',
  'Why you should care about the DOM lifecycle',
  'The hidden cost of hydration',
  'Frameworkless web apps: myth or movement?',
  'Why web performance is your responsibility',
  'The many lives of `position: absolute`',
  'Why your Lighthouse score is lying to you',
  "Dark mode isn't just a toggle",
  'CSS Grid vs Flexbox: when to use which',
  'The art of minimal JavaScript',
  'Declarative UI: more than just JSX',
  'Do you really need that animation?',
  'Custom elements in real-world applications',
  'The return of progressive web apps',
  'Making SPAs feel like MPAs',
  'Why native form controls are better than you think',
  'Stop fighting the browser',
  'One file, one component: a scalable frontend structure',
  'Why most loading spinners are a lie',
  'Stop re-rendering everything: smarter state management strategies',
  'Progressive enhancement is not dead',
  'Why you should care about the DOM lifecycle',
  'The hidden cost of hydration',
  'Frameworkless web apps: myth or movement?',
  'Why web performance is your responsibility',
  'The many lives of `position: absolute`',
  'Why your Lighthouse score is lying to you',
  "Dark mode isn't just a toggle",
  'CSS Grid vs Flexbox: when to use which',
  'The art of minimal JavaScript',
  'Declarative UI: more than just JSX',
  'Do you really need that animation?',
  'Custom elements in real-world applications',
  'The return of progressive web apps',
  'Making SPAs feel like MPAs',
  'Why native form controls are better than you think',
  'Stop fighting the browser',
  'One file, one component: a scalable frontend structure',
  'Why most loading spinners are a lie',
  'Stop re-rendering everything: smarter state management strategies',
  'Progressive enhancement is not dead',
  'Why you should care about the DOM lifecycle',
  'The hidden cost of hydration',
  'Frameworkless web apps: myth or movement?',
  'Why web performance is your responsibility',
  'The many lives of `position: absolute`',
  'Why your Lighthouse score is lying to you',
  "Dark mode isn't just a toggle",
  'CSS Grid vs Flexbox: when to use which',
  'The art of minimal JavaScript',
  'Declarative UI: more than just JSX',
  'Do you really need that animation?',
  'Custom elements in real-world applications',
  'The return of progressive web apps',
  'Making SPAs feel like MPAs',
  'Why native form controls are better than you think',
  'Stop fighting the browser',
  'One file, one component: a scalable frontend structure',
  'Why most loading spinners are a lie',
  'Stop re-rendering everything: smarter state management strategies',
  'Progressive enhancement is not dead',
  'Why you should care about the DOM lifecycle',
  'The hidden cost of hydration',
  'Frameworkless web apps: myth or movement?',
  'Why web performance is your responsibility',
  'The many lives of `position: absolute`',
  'Why your Lighthouse score is lying to you',
  "Dark mode isn't just a toggle",
  'CSS Grid vs Flexbox: when to use which',
  'The art of minimal JavaScript',
  'Declarative UI: more than just JSX',
  'Do you really need that animation?',
  'Custom elements in real-world applications',
  'The return of progressive web apps',
  'Making SPAs feel like MPAs',
  'Why native form controls are better than you think',
  'Stop fighting the browser',
  'One file, one component: a scalable frontend structure',
  'Why most loading spinners are a lie',
  'Stop re-rendering everything: smarter state management strategies',
  'Progressive enhancement is not dead',
  'Why you should care about the DOM lifecycle',
  'The hidden cost of hydration',
  'Frameworkless web apps: myth or movement?',
  'Why web performance is your responsibility',
  'The many lives of `position: absolute`',
  'Why your Lighthouse score is lying to you',
  "Dark mode isn't just a toggle",
  'CSS Grid vs Flexbox: when to use which',
  'The art of minimal JavaScript',
  'Declarative UI: more than just JSX',
  'Do you really need that animation?',
  'Custom elements in real-world applications',
  'The return of progressive web apps',
  'Making SPAs feel like MPAs',
  'Why native form controls are better than you think',
  'Stop fighting the browser',
  'One file, one component: a scalable frontend structure',
  'Why most loading spinners are a lie',
  'Stop re-rendering everything: smarter state management strategies',
  'Progressive enhancement is not dead',
  'Why you should care about the DOM lifecycle',
  'The hidden cost of hydration',
  'Frameworkless web apps: myth or movement?',
  'Why web performance is your responsibility',
  'The many lives of `position: absolute`',
  'Why your Lighthouse score is lying to you',
  "Dark mode isn't just a toggle",
  'CSS Grid vs Flexbox: when to use which',
  'The art of minimal JavaScript',
  'Declarative UI: more than just JSX',
  'Do you really need that animation?',
  'Custom elements in real-world applications',
  'The return of progressive web apps',
  'Making SPAs feel like MPAs',
  'Why native form controls are better than you think',
  'Stop fighting the browser',
  'One file, one component: a scalable frontend structure',
  'Why most loading spinners are a lie',
  'Stop re-rendering everything: smarter state management strategies',
  'Progressive enhancement is not dead',
  'Why you should care about the DOM lifecycle',
  'The hidden cost of hydration',
  'Frameworkless web apps: myth or movement?',
  'Why web performance is your responsibility',
  'The many lives of `position: absolute`',
  'Why your Lighthouse score is lying to you',
  "Dark mode isn't just a toggle",
  'CSS Grid vs Flexbox: when to use which',
  'The art of minimal JavaScript',
  'Declarative UI: more than just JSX',
  'Do you really need that animation?',
  'Custom elements in real-world applications',
  'The return of progressive web apps',
  'Making SPAs feel like MPAs',
  'Why native form controls are better than you think',
  'Stop fighting the browser',
  'One file, one component: a scalable frontend structure',
  'Why most loading spinners are a lie',
  'Stop re-rendering everything: smarter state management strategies',
  'Progressive enhancement is not dead',
  'Why you should care about the DOM lifecycle',
  'The hidden cost of hydration',
  'Frameworkless web apps: myth or movement?',
  'Why web performance is your responsibility',
  'The many lives of `position: absolute`',
  'Why your Lighthouse score is lying to you',
  "Dark mode isn't just a toggle",
  'CSS Grid vs Flexbox: when to use which',
  'The art of minimal JavaScript',
  'Declarative UI: more than just JSX',
  'Do you really need that animation?',
  'Custom elements in real-world applications',
  'The return of progressive web apps',
  'Making SPAs feel like MPAs',
  'Why native form controls are better than you think',
  'Stop fighting the browser',
  'One file, one component: a scalable frontend structure',
  'Why most loading spinners are a lie',
  'Stop re-rendering everything: smarter state management strategies',
  'Progressive enhancement is not dead',
  'Why you should care about the DOM lifecycle',
  'The hidden cost of hydration',
  'Frameworkless web apps: myth or movement?',
  'Why web performance is your responsibility',
  'The many lives of `position: absolute`',
  'Why your Lighthouse score is lying to you',
  "Dark mode isn't just a toggle",
  'CSS Grid vs Flexbox: when to use which',
  'The art of minimal JavaScript',
  'Declarative UI: more than just JSX',
  'Do you really need that animation?',
  'Custom elements in real-world applications',
  'The return of progressive web apps',
  'Making SPAs feel like MPAs',
  'Why native form controls are better than you think',
  'Stop fighting the browser',
  'One file, one component: a scalable frontend structure',
  'Why most loading spinners are a lie',
  'Stop re-rendering everything: smarter state management strategies',
  'Progressive enhancement is not dead',
  'Why you should care about the DOM lifecycle',
  'The hidden cost of hydration',
  'Frameworkless web apps: myth or movement?',
  'Why web performance is your responsibility',
  'The many lives of `position: absolute`',
  'Why your Lighthouse score is lying to you',
  "Dark mode isn't just a toggle",
  'CSS Grid vs Flexbox: when to use which',
  'The art of minimal JavaScript',
  'Declarative UI: more than just JSX',
  'Do you really need that animation?',
  'Custom elements in real-world applications',
  'The return of progressive web apps',
  'Making SPAs feel like MPAs',
  'Why native form controls are better than you think',
  'Stop fighting the browser',
  'One file, one component: a scalable frontend structure',
  'Why most loading spinners are a lie',
  'Stop re-rendering everything: smarter state management strategies',
  'Progressive enhancement is not dead',
  'Why you should care about the DOM lifecycle',
  'The hidden cost of hydration',
  'Frameworkless web apps: myth or movement?',
  'Why web performance is your responsibility',
  'The many lives of `position: absolute`',
  'Why your Lighthouse score is lying to you',
  "Dark mode isn't just a toggle",
  'CSS Grid vs Flexbox: when to use which',
  'The art of minimal JavaScript',
  'Declarative UI: more than just JSX',
  'Do you really need that animation?',
  'Custom elements in real-world applications',
  'The return of progressive web apps',
  'Making SPAs feel like MPAs',
  'Why native form controls are better than you think',
  'Stop fighting the browser',
  'One file, one component: a scalable frontend structure',
  'Why most loading spinners are a lie',
  'Stop re-rendering everything: smarter state management strategies',
  'Progressive enhancement is not dead',
  'Why you should care about the DOM lifecycle',
  'The hidden cost of hydration',
  'Frameworkless web apps: myth or movement?',
  'Why web performance is your responsibility',
  'The many lives of `position: absolute`',
  'Why your Lighthouse score is lying to you',
  "Dark mode isn't just a toggle",
  'CSS Grid vs Flexbox: when to use which',
  'The art of minimal JavaScript',
  'Declarative UI: more than just JSX',
  'Do you really need that animation?',
  'Custom elements in real-world applications',
  'The return of progressive web apps',
  'Making SPAs feel like MPAs',
  'Why native form controls are better than you think',
  'Stop fighting the browser',
  'One file, one component: a scalable frontend structure',
  'Why most loading spinners are a lie',
  'Stop re-rendering everything: smarter state management strategies',
  'Progressive enhancement is not dead',
  'Why you should care about the DOM lifecycle',
  'The hidden cost of hydration',
  'Frameworkless web apps: myth or movement?',
  'Why web performance is your responsibility',
  'The many lives of `position: absolute`',
  'Why your Lighthouse score is lying to you',
  "Dark mode isn't just a toggle",
  'CSS Grid vs Flexbox: when to use which',
  'The art of minimal JavaScript',
  'Declarative UI: more than just JSX',
  'Do you really need that animation?',
  'Custom elements in real-world applications',
  'The return of progressive web apps',
  'Making SPAs feel like MPAs',
  'Why native form controls are better than you think',
  'Stop fighting the browser',
  'One file, one component: a scalable frontend structure',
  'Why most loading spinners are a lie',
  'Stop re-rendering everything: smarter state management strategies',
  'Progressive enhancement is not dead',
  'Why you should care about the DOM lifecycle',
  'The hidden cost of hydration',
  'Frameworkless web apps: myth or movement?',
  'Why web performance is your responsibility',
  'The many lives of `position: absolute`',
  'Why your Lighthouse score is lying to you',
  "Dark mode isn't just a toggle",
  'CSS Grid vs Flexbox: when to use which',
  'The art of minimal JavaScript',
  'Declarative UI: more than just JSX',
  'Do you really need that animation?',
  'Custom elements in real-world applications',
  'The return of progressive web apps',
  'Making SPAs feel like MPAs',
  'Why native form controls are better than you think',
  'Stop fighting the browser',
  'One file, one component: a scalable frontend structure',
  'Why most loading spinners are a lie',
  'Stop re-rendering everything: smarter state management strategies',
  'Progressive enhancement is not dead',
  'Why you should care about the DOM lifecycle',
  'The hidden cost of hydration',
  'Frameworkless web apps: myth or movement?',
  'Why web performance is your responsibility',
  'The many lives of `position: absolute`',
  'Why your Lighthouse score is lying to you',
  "Dark mode isn't just a toggle",
  'CSS Grid vs Flexbox: when to use which',
  'The art of minimal JavaScript',
  'Declarative UI: more than just JSX',
  'Do you really need that animation?',
  'Custom elements in real-world applications',
  'The return of progressive web apps',
  'Making SPAs feel like MPAs',
  'Why native form controls are better than you think',
  'Stop fighting the browser',
  'One file, one component: a scalable frontend structure',
  'Why most loading spinners are a lie',
  'Stop re-rendering everything: smarter state management strategies',
  'Progressive enhancement is not dead',
  'Why you should care about the DOM lifecycle',
  'The hidden cost of hydration',
  'Frameworkless web apps: myth or movement?',
  'Why web performance is your responsibility',
  'The many lives of `position: absolute`',
  'Why your Lighthouse score is lying to you',
  "Dark mode isn't just a toggle",
  'CSS Grid vs Flexbox: when to use which',
  'The art of minimal JavaScript',
  'Declarative UI: more than just JSX',
  'Do you really need that animation?',
  'Custom elements in real-world applications',
  'The return of progressive web apps',
  'Making SPAs feel like MPAs',
  'Why native form controls are better than you think',
  'Stop fighting the browser',
  'One file, one component: a scalable frontend structure',
  'Why most loading spinners are a lie',
  'Stop re-rendering everything: smarter state management strategies',
  'Progressive enhancement is not dead',
  'Why you should care about the DOM lifecycle',
  'The hidden cost of hydration',
  'Frameworkless web apps: myth or movement?',
  'Why web performance is your responsibility',
  'The many lives of `position: absolute`',
  'Why your Lighthouse score is lying to you',
  "Dark mode isn't just a toggle",
  'CSS Grid vs Flexbox: when to use which',
  'The art of minimal JavaScript',
  'Declarative UI: more than just JSX',
  'Do you really need that animation?',
  'Custom elements in real-world applications',
  'The return of progressive web apps',
  'Making SPAs feel like MPAs',
  'Why native form controls are better than you think',
  'Stop fighting the browser',
  'One file, one component: a scalable frontend structure',
  'Why most loading spinners are a lie',
  'Stop re-rendering everything: smarter state management strategies',
  'Progressive enhancement is not dead',
  'Why you should care about the DOM lifecycle',
  'The hidden cost of hydration',
  'Frameworkless web apps: myth or movement?',
  'Why web performance is your responsibility',
  'The many lives of `position: absolute`',
  'Why your Lighthouse score is lying to you',
  "Dark mode isn't just a toggle",
  'CSS Grid vs Flexbox: when to use which',
  'The art of minimal JavaScript',
  'Declarative UI: more than just JSX',
  'Do you really need that animation?',
  'Custom elements in real-world applications',
  'The return of progressive web apps',
  'Making SPAs feel like MPAs',
  'Why native form controls are better than you think',
  'Stop fighting the browser',
  'One file, one component: a scalable frontend structure',
  'Why most loading spinners are a lie',
  'Stop re-rendering everything: smarter state management strategies',
  'Progressive enhancement is not dead',
  'Why you should care about the DOM lifecycle',
  'The hidden cost of hydration',
  'Frameworkless web apps: myth or movement?',
  'Why web performance is your responsibility',
  'The many lives of `position: absolute`',
  'Why your Lighthouse score is lying to you',
  "Dark mode isn't just a toggle",
  'CSS Grid vs Flexbox: when to use which',
  'The art of minimal JavaScript',
  'Declarative UI: more than just JSX',
  'Do you really need that animation?',
  'Custom elements in real-world applications',
  'The return of progressive web apps',
  'Making SPAs feel like MPAs',
  'Why native form controls are better than you think',
  'Stop fighting the browser',
  'One file, one component: a scalable frontend structure',
  'Why most loading spinners are a lie',
  'Stop re-rendering everything: smarter state management strategies',
  'Progressive enhancement is not dead',
  'Why you should care about the DOM lifecycle',
  'The hidden cost of hydration',
  'Frameworkless web apps: myth or movement?',
  'Why web performance is your responsibility',
  'The many lives of `position: absolute`',
  'Why your Lighthouse score is lying to you',
  "Dark mode isn't just a toggle",
  'CSS Grid vs Flexbox: when to use which',
  'The art of minimal JavaScript',
  'Declarative UI: more than just JSX',
  'Do you really need that animation?',
  'Custom elements in real-world applications',
  'The return of progressive web apps',
  'Making SPAs feel like MPAs',
  'Why native form controls are better than you think',
  'Stop fighting the browser',
  'One file, one component: a scalable frontend structure',
  'Why most loading spinners are a lie',
  'Stop re-rendering everything: smarter state management strategies',
  'Progressive enhancement is not dead',
  'Why you should care about the DOM lifecycle',
  'The hidden cost of hydration',
  'Frameworkless web apps: myth or movement?',
  'Why web performance is your responsibility',
  'The many lives of `position: absolute`',
  'Why your Lighthouse score is lying to you',
  "Dark mode isn't just a toggle",
  'CSS Grid vs Flexbox: when to use which',
  'The art of minimal JavaScript',
  'Declarative UI: more than just JSX',
  'Do you really need that animation?',
  'Custom elements in real-world applications',
  'The return of progressive web apps',
  'Making SPAs feel like MPAs',
  'Why native form controls are better than you think',
  'Stop fighting the browser',
  'One file, one component: a scalable frontend structure',
  'Why most loading spinners are a lie',
  'Stop re-rendering everything: smarter state management strategies',
  'Progressive enhancement is not dead',
  'Why you should care about the DOM lifecycle',
  'The hidden cost of hydration',
  'Frameworkless web apps: myth or movement?',
  'Why web performance is your responsibility',
  'The many lives of `position: absolute`',
  'Why your Lighthouse score is lying to you',
  "Dark mode isn't just a toggle",
  'CSS Grid vs Flexbox: when to use which',
  'The art of minimal JavaScript',
  'Declarative UI: more than just JSX',
  'Do you really need that animation?',
  'Custom elements in real-world applications',
  'The return of progressive web apps',
  'Making SPAs feel like MPAs',
  'Why native form controls are better than you think',
  'Stop fighting the browser',
  'One file, one component: a scalable frontend structure',
  'Why most loading spinners are a lie',
  'Stop re-rendering everything: smarter state management strategies',
  'Progressive enhancement is not dead',
  'Why you should care about the DOM lifecycle',
  'The hidden cost of hydration',
  'Frameworkless web apps: myth or movement?',
  'Why web performance is your responsibility',
  'The many lives of `position: absolute`',
  'Why your Lighthouse score is lying to you',
  "Dark mode isn't just a toggle",
  'CSS Grid vs Flexbox: when to use which',
  'The art of minimal JavaScript',
  'Declarative UI: more than just JSX',
  'Do you really need that animation?',
  'Custom elements in real-world applications',
  'The return of progressive web apps',
  'Making SPAs feel like MPAs',
  'Why native form controls are better than you think',
  'Stop fighting the browser',
  'One file, one component: a scalable frontend structure',
  'Why most loading spinners are a lie',
  'Stop re-rendering everything: smarter state management strategies',
  'Progressive enhancement is not dead',
  'Why you should care about the DOM lifecycle',
  'The hidden cost of hydration',
  'Frameworkless web apps: myth or movement?',
  'Why web performance is your responsibility',
  'The many lives of `position: absolute`',
  'Why your Lighthouse score is lying to you',
  "Dark mode isn't just a toggle",
  'CSS Grid vs Flexbox: when to use which',
  'The art of minimal JavaScript',
  'Declarative UI: more than just JSX',
  'Do you really need that animation?',
  'Custom elements in real-world applications',
  'The return of progressive web apps',
  'Making SPAs feel like MPAs',
  'Why native form controls are better than you think',
  'Stop fighting the browser',
  'One file, one component: a scalable frontend structure',
  'Why most loading spinners are a lie',
  'Stop re-rendering everything: smarter state management strategies',
  'Progressive enhancement is not dead',
  'Why you should care about the DOM lifecycle',
  'The hidden cost of hydration',
  'Frameworkless web apps: myth or movement?',
  'Why web performance is your responsibility',
  'The many lives of `position: absolute`',
  'Why your Lighthouse score is lying to you',
  "Dark mode isn't just a toggle",
  'CSS Grid vs Flexbox: when to use which',
  'The art of minimal JavaScript',
  'Declarative UI: more than just JSX',
  'Do you really need that animation?',
  'Custom elements in real-world applications',
  'The return of progressive web apps',
  'Making SPAs feel like MPAs',
];

const chooseAtRandom = (arr) => arr[Math.floor(Math.random() * arr.length)];

form.onsubmit = (e) => {
  e.preventDefault();
  output.innerText = chooseAtRandom(ideas);
};
